version: '3.9'

services:
  habitdbser:
    image: 'postgres'
    ports:
      - "5432:5432"
    container_name: habitdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres


  python_app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: habitapp
    depends_on: 
      - habitdbser
    environment:
      - DB_HOST=habitdbser
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=postgres
    command: ["python3", "habittrackerapp.py"]